apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: webgame
    context: mario
deploy:
  docker:
    images: [webgame]
#deploy:
  #kubectl:
    #manifests:
      #- k8s-*
portForward:
- resourceType: container
  port: 80
  localPort: 8080