apiVersion: v1
kind: Service
metadata:
  name: doom-service
  labels:
    app: doom-deployment
spec:
  ports:
  - port: 80
    targetPort: 6080
  selector:
    app: doom-deployment
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: doom-deployment
spec:
  selector:
    matchLabels:
      app: doom-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: doom-deployment
    spec:
      containers:
      - name: master
        image: beninanutshell/mydosbox:1.1
        ports:
        - containerPort: 6080
---
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: game-2048
spec:
  entryPoints: # We listen to requests coming from ports 80 and 443
    - web
    - websecure
  routes:
    - match: Host(`2048.doom.beninanutshell.com`)
      kind: Rule
      services:
        - name: doom-service # Requests will be forwarded to this service
          port: 80
