---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-argo
  labels:
    app: mario-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mario-argo
  template:
    metadata:
      labels:
        app: mario-argo
    spec:
      containers:
        - image: beninanutshell/webgame:latest
          name: mario-argo
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
  #name: hpa-mario-argo
#spec:
  #scaleTargetRef:
    #apiVersion: apps/v1
    #kind: Deployment
    #name: mario-argo
  #minReplicas: 2
  #maxReplicas: 10
  #metrics:
  #- type: Resource
    #resource:
      #name: memory
      ## targetAverageValue: 200Mi  not work, changed to below
      #targetAverageUtilization: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mario-argo
spec:
  selector:
    app: mario-argo
  ports:
    - port: 80
      targetPort: web
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mario-argo
spec:
  entryPoints: # We listen to requests coming from ports 80 and 443
    - web
    - websecure
  routes:
    - match: Host(`mario-argo.wam.beninanutshell.com`)
      kind: Rule
      services:
        - name: mario-argo # Requests will be forwarded to this service
          port: 80
