name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - 
        name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          DOCKER_HUB_REPOSITORY: webgame

        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
          echo "Pushing image to ECR..."
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:${GITHUB_REF##*/}-$git_hash
          echo "::set-output name=image::$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:${GITHUB_REF##*/}-$git_hash"
      - 
        name: Update Version
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./manifest/k8s-mario.yaml | grep image | cut -d ":" -f3)
          sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm-example/values.yaml
          
      - 
        name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version updated